apiVersion: v1
kind: Service
metadata:
  name: portscanner-svc
  labels:
    app: portscanner
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: portscanner
  sessionAffinity: ClientIP
